# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "my-app"
client_id = "b0dfa1ece0b367e0efaf8fa79882cc27"
application_url = "https://location-opponents-cp-initiated.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://location-opponents-cp-initiated.trycloudflare.com/auth/callback",
  "https://location-opponents-cp-initiated.trycloudflare.com/auth/shopify/callback",
  "https://location-opponents-cp-initiated.trycloudflare.com/api/auth/callback",
  "https://location-opponents-cp-initiated.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-400b7fae.myshopify.com"
